server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oomall_demo?serverTimezone=GMT%2B8
    username: demouser
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # 将包中的类添加为类型别名
  type-aliases-package: com.xmu.oomall.domain
  # mapper.xml所在的位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 是否开启驼峰命名自动映射，即从经典数据库列名 A_COLUMN 映射到经典 Java 属性名 aColumn。
    map-underscore-to-camel-case: true
